version: '3.7'
services:
  server:
    image: kushtaka/kushtakad:0.2.14
    build: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: volume
        source: data
        target: /data

volumes:
  data:
